################################################################################
# common-services configuration file
# start services in order of dependencies
################################################################################

include:
  - /opt/traffic-monitor/docker/frigate/docker-compose-frigate.yaml
  - /opt/traffic-monitor/docker/node-red-tm/docker-compose-node-red-tm.yaml
