# see https://docs.frigate.video/configuration/reference
mqtt:
  enabled: true
  host: 172.18.0.1
  port: 1883

  user: '{FRIGATE_MQTT_USER}'
  password: '{FRIGATE_MQTT_PASSWORD}'

detectors:
#  mycpu:
#    type: cpu
  hailo:
    type: hailo8l
    device: PCIe
model:
# path: plus://5a7fc4be365884ac2ed1616f83f5510a
  path: plus://36114caab18f9af8eb1c526f8624a0ec

ffmpeg:
  hwaccel_args: preset-rpi-64-h264

# This is the "missing" section that links hardware to software
go2rtc:
  streams:
    picam_h264:
      - ffmpeg:device?video=/dev/video0&input_format=h264&video_size=1280x720
#    picam_gs_h264:
#      - rtsp://172.18.0.1:8554/picam_gs_h264
#     - ffmpeg:device?video=/dev/video8&input_format=h264&video_size=1456x1088

cameras:
  picam_h264:
    enabled: true
    type: generic
    ffmpeg:
      inputs:
        - path: rtsp://172.18.0.1:8554/picam_h264
          roles:
            - detect
        #- path: rtsp://172.18.0.1:8554/picam_h264_detect
        #  roles:
        #    - detect
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 5

    motion:
      mask:
        - 0.569,1,0,1,0,0.495,0.51,0.517
        - 0.507,0.414,1,0.448,0.995,0,0.476,0
        - 0.004,0.018,0.003,0.5,0.511,0.515,0.476,0.019
      threshold: 50
      contour_area: 10
      improve_contrast: true
    zones:
      zone_capture:
        coordinates: 0.493,0.252,1,0.265,0.991,0.985,0.563,1
        loitering_time: 0
        inertia: 3
      zone_far:
        coordinates: 0.494,0.25,1,0.265,0.987,0.57,0.545,0.765,0.507,0.515
        inertia: 3
        loitering_time: 0
      zone_radar:
        coordinates: 0.492,0.263,0.99,0.259,0.995,0.981,0.568,0.966
        loitering_time: 0
        inertia: 3
      zone_near:
        coordinates: 0.546,0.739,0.991,0.28,0.99,0.976,0.57,0.969
        loitering_time: 0
        inertia: 3
    review:
      alerts: {}
      detections:
        required_zones:
          - zone_capture
          - zone_far
          - zone_radar
          - zone_near
  picam_gs_h264:
    enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://172.18.0.1:8554/picam_gs_h264
          roles:
            - detect
    detect:
      enabled: false
      width: 1456
      height: 1088
      fps: 5
    zones:
      zone_capture:
        coordinates: 0.848,0.479,0.235,0.558,0.204,0.348,0.396,0.333
        inertia: 3
        loitering_time: 0
      zone_far:
        coordinates: 0.565,0.399,0.363,0.328,0.198,0.334,0.243,0.541
        inertia: 3
        loitering_time: 0
      zone_near:
        coordinates: 0.977,0.523,0.705,0.428,0.243,0.535,0.349,0.82
        inertia: 3
        loitering_time: 0
      zone_radar:
        coordinates: 0.268,0.649,0.915,0.512,0.503,0.358,0.212,0.395
        inertia: 3
        loitering_time: 0
        speed_threshold: 5
        distances: 25,40,25,40
    review:
      alerts:
        required_zones:
          - zone_capture
          - zone_radar
      detections:
        required_zones:
          - zone_radar
          - zone_capture
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: true
      mask:
        - 0.986,0.493,0.18,0.233,0.176,0.01,0.669,0,1,0
        - 0.24,0.637,0.004,0.681,0,0.006,0.158,0.003
objects:
  track:
    - bicycle
    - person
    - car
    - bus
    - motorcycle
    - dog
  filters:
    bicycle:
      min_area: 0
      max_area: 24000000
      min_ratio: 0.2
      max_ratio: 10.0
      min_score: 0.15
      threshold: 0.25
    motorcycle:
      min_area: 0
      max_area: 24000000
      min_ratio: 0.2
      max_ratio: 10.0
      min_score: 0.5
      threshold: 0.8
    person:
      min_area: 0
      max_area: 24000000
      min_ratio: 0.2
      max_ratio: 10.0
      min_score: 0.4
      threshold: 0.5

record:
  enabled: false

snapshots:
  enabled: true
  clean_copy: true
  timestamp: true
  bounding_box: true
  crop: true
  quality: 100
  retain:
    default: 7

version: 0.16-0
semantic_search:
  enabled: false
  model_size: small
face_recognition:
  enabled: false
  model_size: small
lpr:
  enabled: false
classification:
  bird:
    enabled: false
